version: "3.8"
networks:
  mapstore-network:
    driver: bridge

volumes:
  pg_data:
  geoserver_data:
  geoserver_uploads:
  mapstore_data:

services:

  # 1. Base de datos PostGIS (persistencia en pg_data)
  postgres:
    build:
      context: ./docker/postgres/
    image: geosolutions-mapstore/postgis
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geostore
    volumes:
    - pg_data:${PGDATA:-/var/lib/postgresql/data}:rw
    ports:
      - 5432
    networks:
      - mapstore-network

  # 2. GeoServer (configuración en geoserver_data + uploads)
  geoserver:
    image: kartoza/geoserver:2.21.0
    container_name: geoserver
    #restart: always  # Uncomment if you want to always restart
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    ports:
      - "8081:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_uploads:/mnt/uploads
    depends_on:
      - postgres
    networks:
      - mapstore-network

  # 3. MapStore (persistencia en mapstore_data)
  mapstore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OVR: "geostore-datasource-ovr.properties"
        MAPSTORE_WEBAPP_SRC: "./product/target/mapstore.war"
    container_name: mapstore
    command: [ "wait-for-postgres", "postgres", "5432", "postgres", "postgres", "catalina.sh", "run" ]
    depends_on:
      postgres:
        condition: service_healthy
      geoserver:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./docker/geostore-datasource-ovr-postgres.properties:/usr/local/tomcat/conf/geostore-datasource-ovr.properties:ro
      - mapstore_data:/usr/local/tomcat/datadir
    networks:
      - mapstore-network

  # 4. (Opcional) Nginx reverse‑proxy
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./docker/mapstore.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80"
    depends_on:
      - mapstore
    networks:
      - mapstore-network
